### ISSUE TITLE
Automatically call question.refresh_question() when necessary

### ISSUE THREAD

**Issue by stuhlmueller** [oughtinc/ergo#125]
I expected that this would work:

```py
questions = metaculus.get_questions(cat="internal--el-paso")
for question in questions:
    question.show_community_prediction()
```
But I needed this:

```py
questions = metaculus.get_questions(cat="internal--el-paso")
for question in questions:
    question.refresh_question()  # Load detailed question data
    question.show_community_prediction()
```

**Comment by stuhlmueller** [comment]
One idea how to address this: Add a decorator to methods that require detailed info. If they are called and detailed info isn't accessible, load it from Metaculus.

**Comment by brachbach** [comment]
ah interesting.

What actually happened here, historically, was that when I created `get_questions`, I actually thought that it loaded all of the question data including e.g. everything for the community prediction

but clearly it in fact doesn't, because the API accessed by `get_questions_json` doesn't return all of the needed information

My preferred solution would actually be to just have `get_questions` go get all of the information for each question before creating it

That would require an API call for each question

but that should be fine, since `get_questions` should only be used when you're planning to interact with the details of each question; otherwise you can just use `make_questions_df` (which just relies on `get_questions_json` and doesn't make extra API calls)

make sense?

**Comment by brachbach** [comment]
(`refresh_question` is just supposed to be for when you've made a change to the question, i.e. made a prediction on it, and then you want to load in the new data)

**Comment by brachbach** [comment]
(currently waiting for Andreas to provide feedback on how to handle this one)

**Comment by stuhlmueller** [comment]
- Don't think users should have to know about `make_questions_df` separately from `get_questions`. I think there should only be one API call you need to know to load question data from Metaculus, namely `get_questions`.
- In the interest of not overloading the API when people request large numbers of questions, I think it's best not to automatically load the details for each question and only request it when it's needed. Could have an argument `preload_details` to `get_questions` if we want to support loading all detail immediately.

**Comment by brachbach** [comment]
I think those are reasonable points.

But I think that it's pretty bad to be able to create a MetaculusQuestion that doesn't have all the data we normally expect -- now there are basically 2 different kinds of MetaculusQuestion, which seems quite annoying for us to keep track of and deal with.

I think I'd propose:

1. rename `make_questions_df` to `get_questions_info`. It will still do the same thing as currently
2. to discourage people from pounding the Metaculus API, there will be no function to create multiple questions at once. Users will need to do that themselves e.g. by using `get_questions_info` and then something like `questions = [metaculus.get_question(id) for id in questions_info["id"]`

**Comment by stuhlmueller** [comment]
> now there are basically 2 different kinds of MetaculusQuestion, which seems quite annoying for us to keep track of and deal with in the codebase.

My hope was that you can always treat it as if it has all the data (see decorator proposal above; if it doesn't it will automatically load it when needed).

**Comment by stuhlmueller** [comment]
As a temporary measure I'm also fine with just loading all data for all questions (i.e. calling `refresh_question` automatically).

**Comment by brachbach** [comment]
ah got it. Yeah the decorator idea seems good -- I didn't fully understand it at first, sorry!
