### ISSUE TITLE
Add PredictIt API

### ISSUE THREAD

**Issue by AABoyles** [oughtinc/ergo#147]
It would be cool if ergo could expose an API for PredictIt markets so we could draw on PredictIt data and model it with (or against) Metaculus and Foretold,io questions.

**Comment by stuhlmueller** [comment]
Good idea! Looks like they have [an API](https://predictit.freshdesk.com/support/solutions/articles/12000001878-does-predictit-make-market-data-available-via-an-api-) so should be pretty easy.

**Comment by stuhlmueller** [comment]
A few prototypical use cases are:

1. I load one or more distributions from PredictIt, compute an implied distribution for a Metaculus question, and automatically submit the forecast to Metaculus.
2. I load one or more distributions from PredictIt, compute an implied distribution for another PredictIt question, perhaps transform it a bit (because I don't want to bet on my true beliefs, I want some profit margin), and then manually submit the distribution to PredictIt. Ideally this would also be automated, but PredictIt doesn't have a Write API so it's probably too much pain to support it.
3. I load one or more distributions from Metaculus, compute an implied distribution for a PredictIt question, and submit as in 2.

The next steps are:

1. Write out an example for each of 1-3 as code, pretending that we've already implemented the API.
2. Write a spec for the API based on what's needed to make these examples work well, with reasoning for why we made the choices we did.
