### ISSUE TITLE
Expose Max and Min on ContinuousQuestions

### ISSUE THREAD

**Issue by AABoyles** [oughtinc/ergo#153]
I often want to generate predictions for continuous Metaculus questions with the midrange value in mind for one reason or another. Currently, the way (I think) to do this is something like this:

```python 
sum(question.denormalize_samples([0,1]))/2
```

There's nothing inherently wrong with this, but in order to do the denormalization, the question must have the range boundaries baked into it anyway. It would be nice if they were exposed so I could instead do

```python
(question.min + question.max)/2
```

which is somewhat clearer and (to me) more intuitive.

**Comment by stuhlmueller** [comment]
Continuous questions have a `question_range` property which I think is what you're looking for:

![Screen Shot 2020-04-22 at 10 41 07 AM](https://user-images.githubusercontent.com/382515/80014891-d22e7c00-8485-11ea-9c5d-39fd0de830ba.png)

We'll work on better documentation so that things like this are easier to discover.

**Comment by AABoyles** [comment]
Cool, thank you!
