### ISSUE TITLE
Reduce redundancy in plotting code

### ISSUE THREAD

**Issue by stuhlmueller** [oughtinc/ergo#157]

**Comment by djthorne** [comment]
There are two components we can consider in reducing redundancy. 

The first is making the graphs composable, which I now found the syntax for, so that will help

The second is to try to unify the ContinuousQuestion plotting with the DateQuestion plotting. The issue is that some operations need to happen in the normalized scale for dates (but not for the other question types). To unify them we would therefore need to do these operation in normalized space for all Questions. That isn't a big deal, it just involves an unnecessary there and back to normalized space for samples submitted to Linear/Log questions. Given the size of samples we are considering, I'd say we just take the minute performance/parsimony hit for smaller (more readable?) codebase. 

I'll do them in different commits such that we can omit the second one if we decide we don't like it
