### ISSUE TITLE
Debug El Paso predictions with latest version of Ergo

### ISSUE THREAD

**Issue by stuhlmueller** [oughtinc/ergo#162]
Plotting is different now in that it directly plots samples instead of fitting logistic mixture first

**Comment by stuhlmueller** [comment]
Compare all predictions to community, adjust so that they make sense

**Comment by william-r-s** [comment]
I fixed one bug, the ventilation predictions are now no longer suspiciously low. The icu admissions are still a bit lower than community, maybe it's because you need to account for the amount of time that people spend in ventilation/time it takes to move from icu to ventillation, it's not straightforward how to do this.
I think it should close, but not sure, leaving it to @stuhlmueller

**Comment by stuhlmueller** [comment]
Also need to take more samples before submission, current notebook only takes 100 samples. (Larger number of samples caused some issues that need to be debugged.)
