### ISSUE TITLE
Fix prediction of 1st peak

### ISSUE THREAD

**Issue by stuhlmueller** [oughtinc/ergo#173]

**Comment by stuhlmueller** [comment]
Zak:

> doubt it’s directly related to this point, but the question defines the 2-day SMA at day D as the mean of D and the day before D, but our model equates it to the mean of the day before D and the day after D

**Comment by stuhlmueller** [comment]
This prediction doesn't look right:

<img width="532" alt="Screen Shot 2020-04-25 at 8 45 26 AM" src="https://user-images.githubusercontent.com/382515/80298103-f320f680-873d-11ea-8189-a7e0b5a99cfd.png">

**Comment by william-r-s** [comment]
Can you be more specific by what you mean by "doesn't look right"?

**Comment by stuhlmueller** [comment]
No probability mass on lower boundary. It's likely that date is in fact in the past but our prediction on Metaculus doesn't assign probability to that outcome.

**Comment by brachbach** [comment]
Note: I changed this from a catch-all issue to a specific issue about the last thing that was being discussed

**Comment by william-r-s** [comment]
This isn't a mistake, at least it hasn't been a mistake since 2020-04-23 (when the cases peaked again, ruling out any predictions before that date). And cases reached a new peak on 2020-04-26. The community prediction is likely out of date, or they were hedging about the exact criteria for question resolution (which were clarified in the comments).

See:
https://docs.google.com/spreadsheets/d/1MgRZd0iYZCIgQ8KfRJJTnNrdvUfa2KvBHPA5QVjtFnk/edit#gid=0

**Comment by brachbach** [comment]
thanks @william-r-s!
