### ISSUE TITLE
Organize El Paso code in files for collaborative model development

### ISSUE THREAD

**Issue by stuhlmueller** [oughtinc/ergo#178]

**Comment by brachbach** [comment]
There are various bits of code in the El Paso Colab that are:

1. not part of the core model relating the Metaculus questions and the "Model components"
2. not core functionality that should be integrated into the main `ergo` library

These include:

1. "Munge data"
2. Probably a few things in "Model components" and "El Paso Questions" that could be pulled out

We want to take all of this code out of the model and put it in files in an `examples/el-paso` folder in the `ergo` repo

This will make the Colab much shorter and clearer

**Comment by brachbach** [comment]
My current plan for getting the files into Colab is to [load them using urllib](https://stackoverflow.com/questions/17468616/how-do-i-execute-a-python-script-that-is-stored-on-the-internet).

My top alternative is to [clone in the `ergo` repo and access them from there](https://stackoverflow.com/a/49452931/12016768)

But I like the `urllib` idea because it would work for any Python script anywhere on the Internet

Anyone have a different preferred approach?

**Comment by brachbach** [comment]
Update: at least in the case of these scripts, you're gonna want to be able to load them as Python modules. So planning to go for the clone in the repo approach (h/t @stuhlmueller )

**Comment by brachbach** [comment]
Update: I think I'm done with this, in [this Colab](https://colab.research.google.com/drive/1ia9HLtcFnyaIaER-kD-Q9ynY_kZLuWhc#scrollTo=t93CW729i8fi)

But I'd like to get the Colab runing ergo master before merging
