### ISSUE TITLE
Principled solution to `Encoutered nan gradient, stopping early`

### ISSUE THREAD

**Issue by brachbach** [oughtinc/ergo#208]
This pops up fairly often, e.g. with [this pr](https://github.com/oughtinc/ergo/pull/207)

And it does in fact cause the prediction distribution to be a poor fit for the samples (at least in the case of that PR)

Andreas says: i agree this is annoying, i’ve also encountered it. probably the way to debug it is to read this thread: https://github.com/google/jax/issues/475

**Comment by brachbach** [comment]
This pops up fairly often, e.g. with [this pr](https://github.com/oughtinc/ergo/pull/207)

**Comment by william-r-s** [comment]
https://www.metaculus.com/questions/4166/the-lightning-round-tournament-comparing-metaculus-forecasters-to-infectious-disease-experts/
"we're definitely adding very soon a way to import a PDF you generate as just a list of values into Metaculus and it will do the fitting into 5 components for you."
Might make fitting the mixture ourselves redundant, might be worth asking metaculus about an ETA on this

**Comment by stuhlmueller** [comment]
what if their plan to do the fitting is to use our code though

**Comment by william-r-s** [comment]
touche

**Comment by william-r-s** [comment]
If that was the case then they would probably want to do a better job of accounting for the assumptions made in scoring
https://www.metaculus.com/help/faq/#howscore
"Both the player distribution and the community distribution are combined with a uniform distribution such that Pp(x)/Pu(x)>0.02  always. This prevents the player from catastrophic point losses for erroneous over-confidence."

I guess a straightforward reading of this suggests that the logistic distribution is weighted 0.98 and mixed with a uniform distribution weighted 0.02. We could also do this in fitting. I kind of feel like it wouldn't make sense to do this in sampling though.

**Comment by william-r-s** [comment]
Prior to looking at Ben's examples, in the examples I saw it seemed like this was due to the model trying too hard to fit outliers in the examples I saw, and filtering them out worked to get rid of it.

**Comment by william-r-s** [comment]
All of the nan's seem to be caused by values that are too small. If you clip the normalized samples to have minimum 0, then all the mixtures fit reasonably. 

    normalized_samples = q.normalize_samples(q_samples)
    normalized_samples = np.clip(normalized_samples,0,max(normalized_samples))
    mixture = ergo.logistic.fit_mixture(
        normalized_samples, num_samples=5000,verbose=True
    )
    submission = q.get_submission(mixture)

Short term solution:
Add a minimum value based on judgment/data so far for all distributions in the notebook (I think it's mainly the the log distributions). Tricky to do in the current version because community sampling happens in the question decorator. Could move community sampling into a function called in each distribution question, then add the floor after sampling from the community distribution. (This probably makes sense to do anyways, even if the long term solution is implemented)

Long term solution:
Fix the mixture fitting to match the metaculus scoring, by mixing in the uniform distribution and matching how they account for values above/below the limits 

"For questions that restrict the range of possible outcomes, the distributions are truncated to the restricted range and renormalized such that  ∫P(x) dx = 1. For questions with open-ended ranges, the baseline “uniform” distribution contains a 15% probability of the resolution occurring outside of each open boundary."
https://www.metaculus.com/help/faq/#howscore

**Comment by brachbach** [comment]
One other place where this came up: https://github.com/oughtinc/ergo/pull/259
